author = "Lance Akins"
baseURL = "/"
copyright = "All rights reserved - 2018"
description = "Site for learning Hugo and Forestry"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
metadescription = "Lance Lance Revolution Hugo Test Site"
paginate = 5
theme = "hugo-theme-casper-master"
title = "Lance Lance Revolution"
[params]
author = "Lance Akins"
authorbio = ""
authorlocation = "Earth, Milky Way Galaxy"
authorwebsite = ""
cover = "/img/darius-soodmand-116253.jpg"
description = "Welcome to my website"
hjsstyle = "default"
logo = ""
metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
paginatedsections = ["posts"]
[outputs]
  home = [ "HTML", "CSS" ]
